name: Sync parent repo with submodule

on:
  push:
    branches: 
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: security-summer-school/security-summer-school.github.io
          token: ${{ secrets.ESSENTIALS_PRIVATE_TOKEN }}

      - name: Pull and update submodule recursively
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive -- content/en/essentials/

      - name: Commit
        run: |
          git config user.email "essentials-updater@github.com"
          git config user.name "Essentials Track Updater"
          git add content/en/essentials/
          git commit -m "essentials: Update track submodule" || echo "No changes to commit"
          git push
